### ISSUE TITLE
Mounting holes in the SATURN-rpiW-Case_Slideplate do not match with the SATURN case.

### ISSUE THREAD

**Issue by TMillesich** [rkolbi/My_Mars2Pro_Accessories#5]
Affected files:
SATURN-rpiW-Case_Sideplate-a.STL
SATURN-rpiW-Case_Sideplate-b.STL

The mounting holes in the plate do not match with the Saturn case. Only by few millimeters, but enough to miss both tapped holes on a short edge and another one needs some filing for the tapped hole.

I'll check that i can get the correct positions with my sliding caliper and fusion360 a new STL.

**Comment by rkolbi** [comment]
This is the only report of the fitment not being correct. Please let me know what version of the Saturn you are using, what and how you printed this file, and what were you're exact findings with fitment.
